version: "3"
services:
  backupper:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR:-0}
    image: backupper
    working_dir: /app
    volumes: 
      - ./backupper:/app
      - bypy:/root/.bypy
  scheduler:
    build:
      context: .
      dockerfile: ./docker/scheduler/Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR:-0}
    working_dir: /app
    privileged: true
    volumes: 
      - ./scheduler:/app
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  bypy:
