version: "3"
services:
  backupper:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR:-0}
    working_dir: /app
    volumes: 
      - .:/app
      - bypy:/root/.bypy
      - example_data:/backup/example_data
volumes:
  bypy:
  example_data:
    external: true
