version: "3"
services:
  backupper:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR:-0}
    working_dir: /app
    volumes: 
      - .:/app
      - bypy:/root/.bypy
volumes:
  bypy:
