version: "3.2"
services:
  backupper:
    build:
      context: .
      dockerfile: ./docker/backupper/Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR:-0}
    image: backupper
    working_dir: /app
    environment:
      ARCHIVE_NAME_PREFIX: ${ARCHIVE_NAME_PREFIX:-archive}
      ARCHIVE_PASS: ${ARCHIVE_PASS}
    volumes: 
      - ./backupper:/app
      - bypy:/root/.bypy
  scheduler:
    build:
      context: .
      dockerfile: ./docker/scheduler/Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR:-0}
    working_dir: /app
    privileged: true
    environment:
      ARCHIVE_NAME_PREFIX: ${ARCHIVE_NAME_PREFIX:-archive}
      ARCHIVE_PASS: ${ARCHIVE_PASS}
    volumes: 
      - ./scheduler:/app
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  bypy:
