version: "3"
services:
  backupper:
    image: gas1121/backupper:backupper-test
    command: ping localhost
    working_dir: /app
    volumes: 
      - bypy:/root/.bypy
  scheduler:
    image: gas1121/backupper:scheduler-test
    working_dir: /app
    command: ping localhost
    privileged: true
    volumes: 
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  bypy:
